Algoritmo "Qst09Estcdn"

Var

A, B, C: inteiro


Inicio

escreva("Digite um valor para A: ")
leia(A)
escreva("Digite um valor para B: ")
leia(B)
escreva("Digite um valor para C: ")
leia(C)

se (A < B) e (A < C) entao
escreva("O menor valor esta contido em A")
senao
se (B < C) entao
escreva("O menor valor esta contido em B")
senao
escreva("O menor valor esta contido em C")
fimse
fimse

Fimalgoritmo